apiVersion: v1
kind: Service
metadata:
  name: nodekub
spec:
  selector:
    app: nodekub
  ports:
    - port: 80
      targetPort: 3000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodekub
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodekub
  template:
    metadata:
      labels:
        app: nodekub
    spec:
      containers:
        - name: nodekub
          image: chrissvera78/nodekub-js:1.0.0
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_URL
              value: mongodb://mongo:27017/appdist
          imagePullPolicy: Always
